version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: zim-tracking
    ports:
      - 5432:5432
    volumes:
      - .database/postgres:/var/lib/postgresql/data
